[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "catalyst_fund11"
description = "Catalyst Fund 11 Browser"
version = "0.0.1"
dependencies = ["solara==1.23.0"]

[tool.hatch.build]
include = ["**/*.css", "**/*.py", "**/*.md"]
